/*  	Source: 	Drop_User_Tablespaces.psql
 *	Author:		Benjamin A Garza III
 *	Date:		February 8, 2020
 * 	Modified:	March 24, 2020
 *	Class:		CMPS 4928 - Senior Seminar II
 *	Purpose: 	Drop database and tablespaces.
 *
 *  Run:
 *      psql -d thedatabase [-U username -h 167.172.200.202] -f Drop_User_Tablespaces.psql
 */

drop database if exists TheDatabase;
drop tablespace if exists TheTablespaceIndex;
drop tablespace if exists TheTablespace;
