/*  Source:     Create_User_Tablespaces.sql
 *  Author:     Benjamin A Garza III
 *  Date:       February 8, 2020
 *  Class:      CMPS 4928 - Senior Seminar II
 *  Purpose:    Create tablespaces and database.
 *
 *  Run: (as admin/root)
 *  psql -f Create_User_Tablespaces.psql
 */

CREATE TABLESPACE TheTablespace
         --OWNER minibeniitec
         OWNER benjamin
         --LOCATION '/Users/minibeniitec/Desktop/Senior_Project_Database/TheTablespace/';
         LOCATION '/home/senior_project/Senior_Project_Database/TheTablespace/';


CREATE TABLESPACE TheTablespaceIndex
         --OWNER minibeniitec
         OWNER benjamin
         --LOCATION '/Users/minibeniitec/Desktop/Senior_Project_Database/TheTablespace/TheTablespaceIndex/';
         LOCATION '/home/senior_project/Senior_Project_Database/TheTablespace/TheTablespaceIndex/';

CREATE DATABASE TheDatabase
        --OWNER minibeniitec
        OWNER benjamin
        TABLESPACE = TheTablespace;

