/*  	Source: 	Drop_Tables.psql
 *	Author:		Benjamin A Garza III
 *	Date:		February 8, 2020
 *	Class:		CMPS 4928 - Senior Seminar II
 *	Purpose: 	Drop all tables.
 *
 *  Run:
 *      psql -f Drop_Tables.psql TheDatabase Benjamin
 *      psql -f Drop_Tables.psql TheDatabase minibeniitec
 */

drop table if exists items;
drop table if exists products;
drop table if exists waves;
drop table if exists orders;
drop table if exists timers;
drop table if exists humans;
